src/views/docs.py
from flask import Flask, render_template, Blueprint, current_app, redirect
from utils.checks import *
from utils.exceptions import *

docs = Blueprint('docs', __name__, static_folder="static", template_folder="templates")



@docs.route('/get_moduledocs')
def moduledocs():
    return redirect('docs/modules/work_modules/index.html')


@docs.route('/get_apidocs')
def apidocs():
    return redirect('/apidocs/')

src/views/home.py
from flask import Flask, jsonify, request, render_template, Blueprint, flash, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
from utils.forms import *
from utils.models import *
from uuid import uuid4
from utils.token_jwt import create_token
import datetime

home = Blueprint('home', __name__, static_folder="static", template_folder="templates")


@home.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = Customer.query.filter_by(username=username).first()
        if user is None:
            return jsonify({"Error": "Error"}), 400

        if user.password != password:
            return jsonify({"Error": "Error"}), 400
        else:
            login_user(user, remember=True)
            flash('Logged in!', 'success')
            return redirect(url_for('home.get_home'))

    return render_template('login.html', form=form)


@home.route('/')
@home.route('/home')
def get_home():
    return render_template('home.html')

@home.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home.get_home'))

@home.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    
    if form.validate_on_submit():
        name = form.company_name.data
        email = form.email.data
        username = form.username.data
        password = form.password.data
        sub = int(form.sub.data)

        # Use string UUID to avoid conversion problems
        id = str(uuid4())

        sub_end = datetime.date.today() + datetime.timedelta(days=sub*30)

        new_customer = Customer(id, name, email, username, password)
            

        new_sub = Sub(id, sub_end, sub)

        # Commit first because reference is needed for sub
        db.session.add(new_customer)
        db.session.commit()

        db.session.add(new_sub)
        db.session.commit()

        token = create_token(id)

        flash('Registeration succeeded!', 'success')
        return redirect(url_for('home.login'))

    return render_template('register.html', form=form)

@home.route('/profile')
@login_required
def profile():
    id = current_user.id

    result = db.session.query(Customer).join(Sub).filter(Customer.id == id).first()

    company_name = result.name
    username = result.username
    email = result.email
    id = result.id
    sub = str(result.sub.period) + " month(s)"
    due_date = result.sub.end

    return render_template('profile.html', company_name=company_name, username=username, email=email, id=id, sub=sub, due_date=due_date)

src/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="container d-flex">
  <h1 class="display-1 justify-content-center align-self-center mx-auto" id="maintext">
    <u>DIGITAL TWIN</u>
  </h1>
</div>
{% endblock content %}

src/templates/hrefs.html
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/Navigation-with-Search.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">


<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>

src/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Kandi</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/Navigation-with-Search.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/styles.css') }}">
</head>

<body class="cbg">
  <nav class="navbar navbar-light navbar-expand-md navigation-clean-search cnavbg">
    <div class="container">
      <a class="navbar-brand" href="#">Digital Twin</a>
      <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navcol-1">
        <ul class="nav navbar-nav">
          <li class="nav-item" role="presentation">
            <a class="nav-link" href="{{ url_for('home.get_home') }}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Docs</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('docs.apidocs') }}">API</a>
              <a class="dropdown-item" href="{{ url_for('docs.moduledocs') }}">Modules</a>
            </div>
          </li>
        </ul>
        <form class="form-inline mr-auto" target="_self">
          <div class="form-group">
            <label for="search-field"></label>
          </div>
        </form>
      </div>
      {% if current_user.is_authenticated %}
      <a class="btn action-button custom mx-1" role="button" href="{{ url_for('home.profile') }}">Profile</a>
      <a class="btn action-button custom mx-1" role="button" href="{{ url_for('home.logout') }}">Logout</a>
      {% else %}
      <a class="btn action-button custom mx-1" role="button" href="{{ url_for('home.login') }}">Login</a>
      <a class="btn action-button custom mx-1" role="button" href="{{ url_for('home.register') }}">Register</a>
      {% endif %}
    </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} text-center">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}

  {% block content %}{% endblock %}

  <script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='assets/bootstrap/js/bootstrap.min.js') }}"></script>
</body>

</html>

src/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container" style="margin-top: 150px;">
  <form class="border rounded border border-dark bg-white mx-auto p-5" method="POST" action=""
    style="width: 320px;height: 360px;">
    <h4 class="mb-3">Login</h4>
    {{ form.hidden_tag()}}
    <div class="form-group">
      {{ form.username.label(class="form-control-label") }}

      {% if form.username.errors %}
      {{ form.username(class="form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.username.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
        {{ form.username(class="form-control") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.password.label(class="form-control-label") }}

      {% if form.password.errors %}
      {{ form.password(class="form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.password.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
        {{ form.password(class="form-control") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.submit(class="btn btn-primary btn-block cbtnbg custom", style="margin-top: 0px;") }}
    </div>
  </form>
</div>
{% endblock content %}

src/templates/profile.html
{% extends "layout.html" %}
{% block content %}
<div class="container-fluid border rounded border-dark" style="width: 50%;margin-top: 15%;background-color: rgb(255,255,255);">
  <div class="row">
      <div class="col">
          <ul class="nav nav-tabs">
              <li class="nav-item"><a class="nav-link" href="#general" data-toggle="tab">General</a></li>
              <li class="nav-item"><a class="nav-link" href="#billing" data-toggle="tab">Billing</a></li>
          </ul>
      </div>
  </div>
  <div class="row">
      <div class="col">
          <div class="tab-content">
              <div id="general" class="tab-pane active">
                  <div class="row">
                      <div class="col"><label>Company name</label></div>
                      <div class="col"><label>{{ company_name }}</label></div>
                  </div>
                  <div class="row">
                      <div class="col"><label>Username</label></div>
                      <div class="col"><label>{{ username }}</label></div>
                  </div>
                  <div class="row">
                      <div class="col"><label>Email</label></div>
                      <div class="col"><label>{{ email }}</label></div>
                  </div>
                  <div class="row">
                    <div class="col"><label>User ID</label></div>
                    <div class="col"><label>{{ id }}</label></div>
                </div>
              </div>
              <div id="billing" class="tab-pane">
                  <div class="row">
                      <div class="col"><label>Subscription type</label></div>
                      <div class="col"><label>{{ sub }}</label></div>
                  </div>
                  <div class="row">
                      <div class="col"><label>Next due date</label></div>
                      <div class="col"><label>{{ due_date }}</label></div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock content %}

src/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="d-flex justify-content-center" style="margin-top: 150px;">
  <form class="border rounded border-dark bg-white p-5" method="POST" action="" style="width: 450px;height: 600px;">
    <h4 class="mb-3">Register</h4>
    {{ form.hidden_tag()}}
    <div class="form-group">
      {{ form.company_name.label(class="form-control-label") }}

      {% if form.company_name.errors %}
      {{ form.company_name(class="form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.company_name.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
        {{ form.company_name(class="form-control") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.email.label(class="form-control-label") }}

      {% if form.email.errors %}
      {{ form.email(class="form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.email.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
        {{ form.email(class="form-control") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.username.label(class="form-control-label") }}

      {% if form.username.errors %}
      {{ form.username(class="form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.username.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
        {{ form.username(class="form-control") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.password.label(class="form-control-label") }}

      {% if form.password.errors %}
      {{ form.password(class="form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.password.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
        {{ form.password(class="form-control") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.sub.label(class="form-control-label") }}

      {% if form.sub.errors %}
      {{ form.sub(class="form-control is-invalid") }}
      <div class="invalid-feedback">
        {% for error in form.sub.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% else %}
        {{ form.sub(class="form-control") }}
      {% endif %}
    </div>
    <div class="form-group">
      {{ form.submit(class="btn btn-primary btn-block cbtnbg custom", style="margin-top: 0px;") }}
    </div>
  </form>
</div>
{% endblock content %}